Bootstrap: docker
From: ghcr.io/hpcflow/matflow-damask-parse:latest

%post
    mkdir -p /wd
    MY_ENV=matflow_damask_parse_env
    echo "PATH=/opt/conda/envs/$MY_ENV/bin:/opt/conda/condabin:$PATH" >> $SINGULARITY_ENVIRONMENT
    echo "PS1='($MY_ENV) \W$ '" >> $SINGULARITY_ENVIRONMENT

%runscript
    cd /wd
    eval "$@"
